version: '3'
services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=AIzaSyBKWCKyPJjbr_XZCNAqxAXrZ_FQ9jDWYs0
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://localhost:8080/api/v1
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend